//
// Created by Suvan Cheng on 2022/3/12.
//

#ifndef ROLLOFFMODELLIB_SINGLEMODEL_H
#define ROLLOFFMODELLIB_SINGLEMODEL_H



/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class SingleModel */

#ifndef _Included_SingleModel
#define _Included_SingleModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SingleModel
 * Method:    ModelC
 * Signature: ([D[D[DLjava/lang/String;DIIIDDDD)V
 */
JNIEXPORT void JNICALL Java_SingleModel_ModelC
(JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jstring, jdouble, jint, jint, jint, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif

#endif //ROLLOFFMODELLIB_SINGLEMODEL_H
