//
// Created by Suvan Cheng on 2022/3/12.
//

#ifndef ROLLOFFMODELLIB_TIMEMODEL_H
#define ROLLOFFMODELLIB_TIMEMODEL_H

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class TimeModel */

#ifndef _Included_TimeModel
#define _Included_TimeModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TimeModel
 * Method:    ModelC
 * Signature: ([D[D[D[DLjava/lang/String;DIIIDDLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IDD)V
 */
JNIEXPORT void JNICALL Java_TimeModel_ModelC
(JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jstring, jdouble, jint, jint, jint, jdouble, jdouble, jstring, jstring, jstring, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif


#endif //ROLLOFFMODELLIB_TIMEMODEL_H
